<x-layouts.app title="Add food stock">
    <div class="page-head"><div><h1>Add food stock</h1><p class="sub">Type an ingredient, enter its quantity and purchase rate, then press Enter.</p></div></div>
    <section class="card quick-stock-card"><div class="pad"><h2>Quick entry</h2><p class="sub">Every receipt keeps its own purchase cost, so later price changes do not rewrite history.</p></div>
        @if($ingredients->isEmpty())<div class="pad">No ingredients are configured. <a href="{{ route('food.ingredients.index') }}">Add ingredients first</a>.</div>
        @else
        <form class="pad quick-stock-form" method="post" action="{{ route('food.stock.store') }}" data-quick-food-stock>@csrf
            <label class="stock-date"><span>Stock date</span><input type="date" name="effective_date" required value="{{ old('effective_date', now()->toDateString()) }}"></label>
            <label class="stock-name"><span>Ingredient</span><input name="ingredient_name" list="food-ingredient-list" autocomplete="off" maxlength="255" required autofocus placeholder="Start typing ingredient name"><datalist id="food-ingredient-list">@foreach($ingredients as $ingredient)<option value="{{ $ingredient->name }}">{{ $ingredient->purchase_unit }}</option>@endforeach</datalist></label>
            <label class="stock-quantity"><span>Quantity</span><div class="quantity-input"><input name="quantity" type="number" min="0.001" max="100000000" step="0.001" inputmode="decimal" required placeholder="0"><span data-purchase-unit>unit</span></div></label>
            <label class="stock-cost"><span>Purchase rate (₹)</span><div class="quantity-input"><input name="purchase_rate" type="number" min="0" max="1000000000" step="0.01" inputmode="decimal" required placeholder="0.00"><span data-rate-unit>per unit</span></div><small data-total-cost aria-live="polite"></small></label>
            <button class="btn" type="submit">Add stock</button>
        </form>
        <div class="pad quick-entry-message" data-quick-entry-message hidden></div>
        @endif
    </section>
    <section class="card" style="margin-top:24px"><div class="pad"><h2>Recently added</h2></div><div class="table-wrap"><table><thead><tr><th>Ingredient</th><th>Quantity</th><th>Stock date</th><th>Entered</th></tr></thead><tbody data-recent-food-stock>
        @forelse($recent as $movement)<tr><td>{{ $movement->ingredient->name }}</td><td>{{ \App\Support\FoodStockFormatter::quantity((float) $movement->quantity_base, $movement->ingredient->base_unit) }}</td><td>{{ $movement->effective_date->format('d M Y') }}</td><td>{{ $movement->created_at->diffForHumans() }}</td></tr>
        @empty<tr class="empty"><td colspan="4">No food stock has been entered yet.</td></tr>@endforelse
    </tbody></table></div></section>
    <style>
        .quick-stock-form{display:grid;grid-template-columns:170px minmax(280px,1fr) 220px 260px 140px;gap:14px;align-items:start;padding-bottom:30px}.quick-stock-form label{position:relative;display:grid;grid-template-rows:18px 46px;gap:7px;min-width:0;color:#52525b;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.quick-stock-form label>span:first-child{display:flex;align-items:end;white-space:nowrap}.quick-stock-form input{width:100%;height:46px;min-height:46px}.quick-stock-form .btn{width:100%;height:46px;min-height:46px;margin-top:25px;white-space:nowrap}.quick-stock-form small{position:absolute;top:74px;left:0;min-height:17px;color:#6b7280;font-size:11px;font-weight:500;letter-spacing:0;text-transform:none;white-space:nowrap}.quantity-input{display:flex;width:100%;height:46px;min-width:0}.quantity-input input{min-width:0;flex:1}.quantity-input>span{flex:0 0 auto;min-width:70px;max-width:110px;padding:0 10px;display:grid;place-items:center;border:1px solid #d4d4d8;border-left:0;background:#fafafa;color:#52525b;font-size:11px;font-weight:650;letter-spacing:0;text-transform:none;white-space:nowrap}.quick-entry-message{color:#166534;background:#f0fdf4;border-top:1px solid #bbf7d0}@media(max-width:1250px){.quick-stock-form{grid-template-columns:170px minmax(260px,1fr) 220px}.stock-cost{grid-column:2}.quick-stock-form .btn{grid-column:3;margin-top:25px}}@media(max-width:760px){.quick-stock-form{grid-template-columns:1fr 1fr;padding-bottom:34px}.stock-name{grid-column:1/-1}.stock-cost{grid-column:auto}.quick-stock-form .btn{grid-column:auto}}@media(max-width:520px){.quick-stock-form{grid-template-columns:1fr;gap:17px;padding-bottom:18px}.stock-name,.stock-cost,.quick-stock-form .btn{grid-column:auto}.quick-stock-form .btn{margin-top:0}.quick-stock-form small{position:static;margin-top:-2px;white-space:normal}.stock-cost{grid-template-rows:18px 46px auto}}
    </style>
    <script>
    (()=>{const form=document.querySelector('[data-quick-food-stock]');if(!form)return;const ingredients=@json($ingredients->mapWithKeys(fn($ingredient)=>[$ingredient->name=>['unit'=>$ingredient->purchase_unit,'base_unit'=>$ingredient->base_unit,'factor'=>(float)$ingredient->purchase_to_base]]));const name=form.elements.ingredient_name,quantity=form.elements.quantity,rate=form.elements.purchase_rate,unit=form.querySelector('[data-purchase-unit]'),rateUnit=form.querySelector('[data-rate-unit]'),total=form.querySelector('[data-total-cost]'),message=document.querySelector('[data-quick-entry-message]');const update=()=>{const purchaseUnit=ingredients[name.value]?.unit||'unit';unit.textContent=purchaseUnit;rateUnit.textContent='per '+purchaseUnit;const price=Number(rate.value),count=Number(quantity.value);total.textContent=count>0&&Number.isFinite(price)?`Total purchase cost: ₹${(price*count).toFixed(2)}`:'';};[name,quantity,rate].forEach(input=>input.addEventListener('input',update));form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('button');button.disabled=true;try{const response=await fetch(form.action,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':form.querySelector('[name=_token]').value},body:new FormData(form)});const body=await response.json();if(!response.ok)throw new Error(Object.values(body.errors||{}).flat()[0]||body.message||'Stock could not be added.');message.hidden=false;message.textContent='✓ '+body.message;window.notify?.({title:'Stock added',message:body.message});name.value='';quantity.value='';rate.value='';unit.textContent='unit';rateUnit.textContent='per unit';total.textContent='';name.focus();}catch(error){window.notify?.({type:'error',message:error.message});}finally{button.disabled=false;}});update();})();
    </script>
</x-layouts.app>
