<x-layouts.app title="Product mappings">
<div class="page-head"><div><a class="settings-back" href="{{ route('settings.index') }}">← Settings</a><h1>Product mappings</h1><p class="sub">Exact POS identities and excise code + bottle-size identities. Only mappings you save are reused.</p></div><div class="actions"><a class="btn" href="{{ route('uploads.pos') }}">Map POS items</a><a class="btn secondary" href="{{ route('uploads.excise') }}">Map indent items</a></div></div>
<section class="card"><div class="pad"><h2>{{ $mappings->count() }} active mappings</h2><p class="sub">Create or correct mappings in the document preview, where the source volume and serving rule can be verified. A correction never rewrites submitted history.</p></div>
<div class="table-wrap"><table data-spirit-filter><thead><tr><th>Source item</th><th>Source</th><th>Stock brand / drink</th><th>Consumption rule</th><th>Actions</th></tr></thead><tbody>
@forelse($mappings as $mapping)
@php($rule = json_decode($mapping->rules, true))
<tr data-spirit-type="{{ $mapping->spirit_type ?? '' }}"><td>{{ $mapping->source_name }}</td><td>{{ strtoupper($mapping->source) }}</td><td>{{ $mapping->product_name ?? $mapping->recipe_name ?? 'No alcohol stock' }} @if($mapping->bottle_size_ml) · {{ (int)$mapping->bottle_size_ml }} ml @endif</td><td>@if($rule['kind'] === 'bottle'){{ $rule['bottles_per_sale'] }} bottle(s) per unit @elseif($rule['kind'] === 'measured'){{ $rule['serving_ml'] }} ml per serving @elseif($rule['kind'] === 'recipe')Saved cocktail recipe @else Explicitly ignored @endif</td><td><form method="post" action="{{ route('mappings.reviewed.destroy', $mapping->id) }}" onsubmit="return confirm('Remove this mapping from future uploads and unsubmitted previews? Posted stock will not change.')">@csrf @method('DELETE')<button class="btn secondary">Remove mapping</button></form></td></tr>
@empty<tr><td colspan="5" class="empty">Upload a document and save its reviewed mappings to begin.</td></tr>@endforelse
</tbody></table></div></section>
@if($legacyMappings->isNotEmpty())
<section class="card" style="margin-top:20px"><div class="pad"><h2>Previous name-only mappings</h2><p class="sub">Preserved for reference. Re-save these from a new upload once to confirm exact sizes and sale conversions. Older mappings omitted these details and are not silently trusted by the new stock engine.</p></div><div class="table-wrap"><table data-spirit-filter><thead><tr><th>Source item</th><th>Source</th><th>Previous brand</th><th></th></tr></thead><tbody>@foreach($legacyMappings as $mapping)<tr data-spirit-type="{{ $mapping->product?->spirit_type ?? '' }}"><td>{{ $mapping->source_name }}</td><td>{{ $mapping->source }}</td><td>{{ $mapping->product?->name ?? 'Unavailable' }}</td><td><form method="post" action="{{ route('mappings.destroy', $mapping->id) }}" onsubmit="return confirm('Delete this old name-only mapping?')">@csrf @method('DELETE')<button class="btn secondary">Delete</button></form></td></tr>@endforeach</tbody></table></div></section>
@endif
<style>.settings-back{display:inline-block;margin-bottom:9px;color:#c2410c;text-decoration:none;font-size:12px;font-weight:650}</style>
</x-layouts.app>
